### ISSUE TITLE
syosetu-list-number使用中发现一个问题

### ISSUE THREAD

**Issue by nyan-sherry** [bluelovers/gm-user-scripts#1]
在插件启用后，短篇小说（即点开直接是正文不分任何章节的）正文会消失。
https://ncode.syosetu.com/n9247ff/
↑例

因为没有特别关注过更新，感觉上好像是在更新添加了复制功能之后出现的问题。
所以来汇报一下~

**Comment by bluelovers** [comment]
@nyan-sherry 這各 BUG 太少見 導致我 忘記修了

晚點有空會修正這個問題

感謝回報
